// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Msyu9Gates.Data;

#nullable disable

namespace Msyu9Gates.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250829044719_ApplicationDbContext_UpdateModels")]
    partial class ApplicationDbContext_UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Msyu9Gates.Lib.Models.AttemptModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttemptValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AttemptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChapterModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChapterModelId");

                    b.HasIndex("UserId", "GateId", "ChapterId");

                    b.ToTable("AttemptsDb");
                });

            modelBuilder.Entity("Msyu9Gates.Lib.Models.ChapterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DateCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateUnlockedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiffiutyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GateId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GateModelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Narrative")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RouteGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GateModelId");

                    b.HasIndex("GateId", "ChapterNumber")
                        .IsUnique();

                    b.ToTable("ChaptersDb");
                });

            modelBuilder.Entity("Msyu9Gates.Lib.Models.GateModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conclusion")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateUnlocked")
                        .HasColumnType("TEXT");

                    b.Property<int>("GateNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GateOverallDifficultyLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Narrative")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GateNumber")
                        .IsUnique();

                    b.ToTable("GatesDb");
                });

            modelBuilder.Entity("Msyu9Gates.Lib.Models.KeyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChapterModelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DateDiscoveredUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Discovered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChapterModelId");

                    b.HasIndex("KeyNumber", "KeyValue")
                        .IsUnique();

                    b.ToTable("KeysDb");
                });

            modelBuilder.Entity("Msyu9Gates.Lib.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastLoginUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.ToTable("UsersDb");
                });

            modelBuilder.Entity("Msyu9Gates.Lib.Models.AttemptModel", b =>
                {
                    b.HasOne("Msyu9Gates.Lib.Models.ChapterModel", null)
                        .WithMany("Attempts")
                        .HasForeignKey("ChapterModelId");
                });

            modelBuilder.Entity("Msyu9Gates.Lib.Models.ChapterModel", b =>
                {
                    b.HasOne("Msyu9Gates.Lib.Models.GateModel", null)
                        .WithMany("Chapters")
                        .HasForeignKey("GateModelId");
                });

            modelBuilder.Entity("Msyu9Gates.Lib.Models.KeyModel", b =>
                {
                    b.HasOne("Msyu9Gates.Lib.Models.ChapterModel", null)
                        .WithMany("Keys")
                        .HasForeignKey("ChapterModelId");
                });

            modelBuilder.Entity("Msyu9Gates.Lib.Models.ChapterModel", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Keys");
                });

            modelBuilder.Entity("Msyu9Gates.Lib.Models.GateModel", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
