// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Msyu9Gates.Data;

#nullable disable

namespace Msyu9Gates.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250720035755_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Msyu9Gates.Data.Models.GateModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GateDifficulty")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Keys")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GatesDb");
                });

            modelBuilder.Entity("Msyu9Gates.Data.Models.KeyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDiscovered")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Discovered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KeysDb");
                });
#pragma warning restore 612, 618
        }
    }
}
