// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Msyu9Gates.Data;

#nullable disable

namespace Msyu9Gates.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250722173013_Rebuild")]
    partial class Rebuild
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Msyu9Gates.Data.Models.ChapterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chapter")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateUnlocked")
                        .HasColumnType("TEXT");

                    b.Property<int>("GateId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChaptersDb");
                });

            modelBuilder.Entity("Msyu9Gates.Data.Models.KeyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDiscovered")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Discovered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KeysDb");
                });
#pragma warning restore 612, 618
        }
    }
}
